#!/bin/bash

inotifywait -r -e create -m --format '%w%f' /etc/incoming_config | \
    while read f; do
    if [[ $f == *"ISDIR"* ]]; then
        :
    else
        mv $f /root/capstone/incoming_config
    fi
done
